// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/tabakazu/webapi-app/infra/web"
)

// Injectors from wire.go:

func InitializeWebApp() *web.Server {
	server := web.NewServer()
	return server
}
