// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/tabakazu/webapi-app/adapter/rest"
	"net/http"
)

// Injectors from wire.go:

func InitializeWebApp() *http.Server {
	router := rest.NewRouter()
	server := rest.NewServer(router)
	return server
}
