version: '3.7'

services:
  goose:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /go/src/github.com/tabakazu/goose-demo
    volumes:
      - .:/go/src/github.com/tabakazu/goose-demo
      - go_modules:/go/pkg/mod
    environment:
      - DATABASE_URL=root:@tcp(mysql:3306)/goose_demo?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=goose_demo
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  go_modules:
  mysql_data:
