version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=root:@tcp(mysql:3306)/sqlx_demo?charset=utf8&parseTime=True&loc=Local
    volumes:
      - .:/go/src/github.com/tabakazu/sqlx-demo
      - go_modules:/go/pkg/mod
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=sqlx_demo
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  go_modules:
  mysql_data:
